charts:
  - name: z2jh-extended
    # TODO: decide if eu.gcr.io or k8s.gcr.io should be used.
    imagePrefix: eu.gcr.io/jupyter-se/
    images:
      hub:
        imageValuesPath: jupyterhub.hub.image
        buildArgs:
          JUPYTERHUB_VERSION: 0.8.1
      singleuser:
        imageValuesPath: jupyterhub.singleuser.image
        buildArgs:
          JUPYTERHUB_VERSION: 0.8.1
      image-awaiter:
        imageValuesPath: jupyterhub.imagePuller.hook.image
      # nfs-server:
      #   imageValuesPath: nfsServer.image
      # assistant:
      #   imageValuesPath: assistant.image
