apiVersion: v1
description: An extended Zero-to-JupyterHub-K8s installation.
name: z2jh-extended
version: lab-update-02
sources:
  - https://github.com/consideRatio/z2jh-extended
maintainers:
  - name: Erik Sundell
