# Helm documentation regarding values.yaml files
# https://docs.helm.sh/chart_template_guide/#values-files

# Helm documentation regarding overriding a subcharts values
# https://docs.helm.sh/chart_template_guide/#overriding-values-from-a-parent-chart

nfsServer:
  storage: 10Gi
  resources:
    requests:
      cpu: 1
      memory: 2Gi

# JupyterHub subchart override
jupyterhub:
  hub:
    service:
      type: ClusterIP
    baseUrl: /
    ### cookieSecret OVERRIDDEN in secret-values.yaml
    cookieSecret:
    publicURL:
    uid: 1000
    fsGid: 1000
    nodeSelector: {}
    concurrentSpawnLimit: 64
    activeServerLimit:
    db:
      type: sqlite-pvc
      upgrade:
      pvc:
        annotations: {}
        selector: {}
        accessModes:
          - ReadWriteOnce
        storage: 1Gi
        subPath:
        storageClassName:
      url:
    labels: {}
    ### extraConfig MODIFIED
    extraConfig: |
      # Useful functions duplicated from z2jh/images/hub/jupyterhub_config.py
      # See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/374
      # -----------------------------------------------------------------------
      import os
      import yaml

      def get_config(key, default=None):
          """
          Find a config item of a given name & return it

          Parses everything as YAML, so lists and dicts are available too
          """
          path = os.path.join('/etc/jupyterhub/config', key)
          try:
              with open(path) as f:
                  data = yaml.safe_load(f)
                  return data
          except FileNotFoundError:
              return default

      def get_secret(key, default=None):
          """Get a secret from /etc/jupyterhub/secret"""
          path = os.path.join('/etc/jupyterhub/secret', key)
          try:
              with open(path) as f:
                  return f.read().strip()
          except FileNotFoundError:
              return default
      # -----------------------------------------------------------------------

      # Auth
      from oauthenticator.microsoft import MicrosoftOAuthenticator
      class LearnetAuthenticator(MicrosoftOAuthenticator):  
          from tornado import gen

          @gen.coroutine
          def pre_spawn_start(self, user, spawner):
              auth_state = yield user.get_auth_state()
              if not auth_state:
                  return

              # ENV
              spawner.environment['AUTH_USERNAME'] = str(user.name)
              spawner.environment['AUTH_ACCESS_TOKEN'] = str(auth_state['access_token'])
              spawner.environment['AUTH_ID'] = str(auth_state['microsoft_user']['id'])
              spawner.environment['AUTH_USER_PRINCIPAL_NAME'] = str(auth_state['microsoft_user']['userPrincipalName'])
              spawner.environment['AUTH_DISPLAY_NAME'] = str(auth_state['microsoft_user']['displayName'])
              spawner.environment['AUTH_GIVEN_NAME'] = str(auth_state['microsoft_user']['givenName'])
              spawner.environment['AUTH_SURNAME'] = str(auth_state['microsoft_user']['surname'])
              spawner.environment['AUTH_MAIL'] = str(auth_state['microsoft_user']['mail'])
              spawner.environment['AUTH_MOBILE_PHONE'] = str(auth_state['microsoft_user']['mobilePhone'])
              spawner.environment['AUTH_BUSINESS_PHONES'] = str(auth_state['microsoft_user']['businessPhones'])
              spawner.environment['AUTH_JOB_TITLE'] = str(auth_state['microsoft_user']['jobTitle'])
              spawner.environment['AUTH_OFFICE_LOCATION'] = str(auth_state['microsoft_user']['officeLocation'])
              spawner.environment['AUTH_PREFERRED_LANGUAGE'] = str(auth_state['microsoft_user']['preferredLanguage'])

              # Decide what type of user this is
              if str(auth_state['microsoft_user']['jobTitle']) == 'Lärare':
                edu_role = 'instructor'
              elif str(auth_state['microsoft_user']['jobTitle']) == 'Elev':
                edu_role = 'student'
              else:
                edu_role = 'unknown'

              spawner.environment['EDU_ROLE'] = edu_role

              # LABELS
              # c.KubeSpawner.singleuser_extra_labels = get_config('singleuser.extra-labels', {})
              spawner.singleuser_extra_labels['edu-role'] = edu_role
              spawner.user_storage_extra_labels['edu-role'] = edu_role

              # ANNOTATIONS
              # - School info?
              # config c.KubeSpawner.singleuser_extra_annotations = Dict()


              # HOOKS
              # https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L613
              spawner.singleuser_lifecycle_hooks = {
                'postStart': {
                  'exec': {
                    'command': ['/bin/sh', '-c', 'echo Hello Im $(whoami) from the postStart handler > /home/jovyan/message']
                  }
                }
              }

              # USER / GROUP
              # c.KubeSpawner.singleuser_uid = get_config('singleuser.uid')
              # c.KubeSpawner.singleuser_fs_gid = get_config('singleuser.fs-gid')
              # TODO: figre out if setting these differently based on the user
              # could eliminate the need to create multiple images.
              # - https://github.com/jupyterhub/kubespawner/issues/18#issuecomment-272633065
              # NOTE:
              # - I can only setup permissions for pre-created folders, right? Or is regexp permissions possible?
              
              # IMAGE
              # c.KubeSpawner.singleuser_image_spec = os.environ['SINGLEUSER_IMAGE']              
              # TODO: figure out how to set this properly

              # VOLUME / MOUNT
              # TODO: I know i need to do this in the end to setup different volumes for my user...
              # c.KubeSpawner.volumes.extend(get_config('singleuser.storage.extra-volumes', []))
              # TODO (later): figure out how to set this properly, it is currently setting it as...
              # extraVolumes: ### MODIFIED
              # - name: volume-nbgrader
              #   persistentVolumeClaim:
              #     claimName: nfs-pvc

              # c.KubeSpawner.volume_mounts.extend(get_config('singleuser.storage.extra-volume-mounts', []))
              # TODO (later): figure out how to set this properly, it is currently setting it as...
              # extraVolumeMounts: ### MODIFIED
              #   - name: volume-nbgrader
              #     mountPath: /srv/nbgrader/exchange
              #     subPath: ''


      c.JupyterHub.authenticator_class = LearnetAuthenticator
      # Import auth-information from extraConfigMap set in secret-values.yaml
      c.MicrosoftOAuthenticator.client_id = get_config('custom.client-id')
      c.MicrosoftOAuthenticator.client_secret = get_config('custom.client-secret')
      c.MicrosoftOAuthenticator.oauth_callback_url = get_config('custom.callback-url')
      c.MicrosoftOAuthenticator.hosted_domain = get_config('custom.hosted-domain')
      c.MicrosoftOAuthenticator.login_service = get_config('custom.login-service')
      email_domain = get_config('custom.hosted-domain')
    ### extraConfigMap OVERRIDDEN in secret-values.yaml
    extraConfigMap:
      client-id: ''
      client-secret: ''
      callback-url: ''
      hosted-domain: ''
      login-service: ''
    ### extraEnv OVERRIDDEN in secret-values.yaml
    extraEnv: {}
    extraContainers: []
    # image WRITTEN by ../build.py
    image:
      name: eu.gcr.io/jupyter-se/hub
      tag: 0cb1fe5
    resources:
      requests:
        cpu: 0.2
        memory: 512Mi
    services: {}
    imagePullPolicy: IfNotPresent

  rbac:
    enabled: true

  proxy:
    ### secretToken OVERRIDDEN in secret-values.yaml
    secretToken: ''
    service:
      type: LoadBalancer
      labels: {}
      annotations: {}
      nodePorts:
        http:
        https:
    chp:
      image:
        name: jupyterhub/configurable-http-proxy
        tag: 3.0.0
        pullPolicy: IfNotPresent
      cmd:
        - configurable-http-proxy
        - --ip=0.0.0.0
        - --port=8000
        - --api-ip=0.0.0.0
        - --api-port=8001
        - --default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
        - --error-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
        - --log-level=debug
      resources:
        requests:
          cpu: 0.2
          memory: 512Mi
    nginx:
      image:
        name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
        tag: 0.9.0
        pullPolicy: IfNotPresent
      proxyBodySize: 64m
      resources: {}
    lego:
      image:
        name: jetstack/kube-lego
        # We need a couple of fixes related to ingress.provider that are in master
        # When 0.1.6 is released, switch to that!
        tag: master-2368
      resources: {}
    labels:
    nodeSelector: {}
    https:
      enabled: true
      type: letsencrypt
      letsencrypt:
        ### contactEmail OVERRIDDEN in secret-values.yaml
        contactEmail: ''
      manual:
        key:
        cert:
      ### hosts OVERRIDDEN in secret-values.yaml
      hosts: []


  # Google OAuth secrets
  auth:
    type: dummy
    whitelist:
      users:
    admin:
      access: true
      users:
        - erik.sundell ### MODIFIED
    dummy:
      password:
    state:
      ### enabled MODIFIED from false
      enabled: true
      ### cryptoKeys OVERRIDDEN in secret-values.yaml
      cryptoKey:

  singleuser:
    extraLabels: {}
    extraEnv: {}
    lifecycleHooks:
    initContainers:
    nodeSelector: {}
    uid: 1000
    fsGid: 1000
    storage:
      type: dynamic
      ### extraVolumes MODIFIED
      extraVolumes:
        - name: volume-nbgrader
          persistentVolumeClaim:
            claimName: nfs-pvc
      ### extraVolumeMounts MODIFIED
      extraVolumeMounts:
        - name: volume-nbgrader
          mountPath: /srv/nbgrader/exchange
          # subPath: ''
      static:
        pvcName:
        subPath: '{username}'
      ### capacity MODIFIED from 10Gi
      capacity: 256Mi
      homeMountPath: /home/jovyan
      dynamic:
        storageClass:
    # image WRITTEN by ../build.py
    image:
      name: eu.gcr.io/jupyter-se/singleuser
      tag: 0cb1fe5
    startTimeout: 300
    cpu:
      limit:
      ### guarantee MODIFIED from
      guarantee: 0.5
    memory:
      limit:
      ### guarantee MODIFIED from 1G
      guarantee: 1G
    cmd: jupyterhub-singleuser

  prePuller:
    enabled: true
    image:
      name: yuvipanda/image-allnodes-puller
      tag: v0.8

  ingress:
    enabled: false
    annotations: {}
    hosts: []
    tls:

  cull:
    enabled: true
    users: false
    ### timeout MODIFIED from 3600
    timeout: 900
    ### every MODIFIED from 600
    every: 150

